os: Visual Studio 2017

init:
  - git config --global core.autocrlf input

build_script:
  - cmd: echo /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" >> msbuild.rsp
  - cmd: taskkill /f /im MSBuild.exe /fi "memusage gt 40" 2>NUL
  - cmd: corebuild.cmd /restore
  - cmd: corebuild.cmd /release
  - cmd: taskkill /f /im MSBuild.exe /fi "memusage gt 40" 2>NUL

nuget:
  disable_publish_on_pr: false
  
artifacts:
  - path: out\*.nupkg
    name: Package
  - path: out\*.html
    name: Test
